### ISSUE TITLE
inconsistent line breaks in /dicts/netgear

### ISSUE THREAD

**Issue by resistor4u** [soxrok2212/PSKracker#10]
Did you intend for lines in `/pskracker/dicts/netgear/adjective_large.txt` to terminate in newlines? As far as I can tell, the other files end in \r\n.
EDIT: https://hashcat.net/forum/thread-6170-post-38094.html#pid38094

**Comment by soxrok2212** [comment]
The netgear lists were compiled by @gearhjunkie 
I personally am not sure what the intentions were there... it was likely just done on a Windows system.

**Comment by gearhjunkie** [comment]
Somehow the line endings were converted during transfer.  I have fixed it so the lines now end with \r\n.
