### ISSUE TITLE
File adjective.txt, terrrific --> terrific (typo)

### ISSUE THREAD

**Issue by cpmitch** [soxrok2212/PSKracker#14]
Hello-  Thanks tons for your work here. Please correct a small typo in file adjective.txt: terrrific should be terrific. Cheers.

**Comment by kimocoder** [comment]
I sent a PR to fix it. This issue may be closed, thanks for the heads up

**Comment by soxrok2212** [comment]
Fixed the adjective and netgear lists. See https://github.com/soxrok2212/PSKracker/commit/61de4fbfb74c8eaf7b4cf2d136a2e27984f0c37b
