### ISSUE TITLE
Belkin algorithm not complete

### ISSUE THREAD

**Issue by soxrok2212** [soxrok2212/PSKracker#16]
There are some older Belkin devices that do not follow the same algorithm, though they do use known variants.

**Comment by adde88** [comment]
Thought i'd just give some input regarding PSKracker on Raspberry Pi 3 B+ (Kali Rolling) aarch64
Seems to work flawlessly . Compilation and everything goes well, without any issues. :)

**Comment by soxrok2212** [comment]
Thanks. There are a few variants to this algorithm that I have yet to implement. That’s all.
