### ISSUE TITLE
c best of the best language for implementations when have cpu higher, and internet connection, have been in lisp.common. is cool. and boos. can you make a one script with lisp. for lnux ubuntu.

### ISSUE THREAD

**Issue by darknodi** [soxrok2212/PSKracker#19]
@PurpleNinja225 @soxrok2212 @wiire-a @Allesanddro @gearhjunkie

**Comment by Allesanddro** [comment]
Uh sir ? How about opening that english text book?

**Comment by soxrok2212** [comment]
If you ask everything as if you had a lisp, there's a 0.00000001% chance I'll do it.
