### ISSUE TITLE
make: *** [src/pskracker.o] Error 1 make install error (

### ISSUE THREAD

**Issue by darknodi** [soxrok2212/PSKracker#20]
name@name:~/Downloads/pskracker$ make
cc -Wno-unused -Wno-return-type  -c -o src/pskracker.o src/pskracker.c
In file included from src/pskracker.c:31:0:
src/att.c: In function ‘genpass589’:
src/att.c:46:21: error: ‘__int128’ is not supported for this target
  y = (uint64_t) ( ((__int128)y * (__int128)1000000000000000000ull) >> 61 ); 
                     ^
src/att.c:46:35: error: ‘__int128’ is not supported for this target
  y = (uint64_t) ( ((__int128)y * (__int128)1000000000000000000ull) >> 61 ); 
                                   ^
src/att.c:46:2: warning: right shift count >= width of type [enabled by default]
  y = (uint64_t) ( ((__int128)y * (__int128)1000000000000000000ull) >> 61 ); 
  ^
src/att.c: In function ‘genpass599’:
src/att.c:66:2: warning: left shift count >= width of type [enabled by default]
  uint64_t one = (double) (x * ((1l << 32) + 2));
  ^
make: *** [src/pskracker.o] Error 1
name@name:~/Downloads/pskracker$  @soxrok2212

**Comment by soxrok2212** [comment]
Would you like to give more information? You posted a failed compile. What OS? 32-bit or 64-bit? And why did you strikethrough everything?

**Comment by darknodi** [comment]
Linux name 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:18 UTC 2016 i686 i686 i686 GNU/Linux

Cub/Linux i386.iso 

Samsung Device ( Manufacturer Laptop Netbook Portable ) 
Firmware Manufactuer: 
Samsung N150 Laptop Netbook Portable
Firmware Manufacturer Architecture Intel Processors ( 32-bit ) 
Power frequences intel
Intel(R) Atom(TM) CPU N450   @ 1.66GHz		: 1000,00MHz
Intel(R) Atom(TM) CPU N450   @ 1.66GHz		: 1667,00MHz
Memory RAM: -Memory-
Total Memory		: 2052580 kB
@soxrok2212

**Comment by darknodi** [comment]
I have following your orders. 

git clone https://github.com/soxrok2212/pskracker
cd pskracker
sudo apt update ( to finds dependencies from the modules ) 
for execute make, and make install 
should sudo chmod a+x * or sudo chmod 777 * 
and, sudo  make, and sudo make install. 

@soxrok2212

**Comment by darknodi** [comment]
@soxrok2212 I would want to have faster work, as have said, Linux Torvalds, I work faster. 

should not sudo, sudo chmod.... to give permissions... to the scripts. modules.

**Comment by soxrok2212** [comment]
i386 does not support __int128. You’d need to upgrade to a processor that does (many 64 but processors do).

**Comment by darknodi** [comment]
@soxrok2212 understand......
