### ISSUE TITLE
found a new word.

### ISSUE THREAD

**Issue by paul-jackson-dev** [soxrok2212/PSKracker#33]
coffee

48cd6c7bcf59d27ab0d7f798055d2116:4cabf8252560:0071477d7d9f:SpectrumSetup-61:coffeeloyal571

![Screenshot 2022-11-17 203256](https://user-images.githubusercontent.com/42046646/202603522-963383ae-0a98-4910-beec-01772de5a36f.png)

**Comment by soxrok2212** [comment]
Added, thanks!

**Comment by paul-jackson-dev** [comment]
nation

found another word in the wild.
27422cf27424bc03ec499a351a201326:147d054bbba6:02ed018e5e19:SpectrumSetup-A5:nicenation029

**Comment by soxrok2212** [comment]
> nation
> 
> found another word in the wild. 27422cf27424bc03ec499a351a201326:147d054bbba6:02ed018e5e19:SpectrumSetup-A5:nicenation029

Please make a PR :)
