### ISSUE TITLE
Add more keyspaces to the list

### ISSUE THREAD

**Issue by moonlightz** [soxrok2212/PSKracker#34]
I can see MEO-xxxxxx listed, where x is 0123456789ABCDEF.
MEO was a television/net service launched by Portugal Telecom (PT), now owned by Altice. Thomson, Zyxel, Technicolor routers were some of the routers offered to users.
Routers with MAC address starting 00:06:91 (Altice Labs Fibergateway 2017), the keyspace is 0123456789abcdef 10 length.
Routers with MAC-address starting CC:19:A8 (Altice Fibergateway newer version), 9C:97:26 (Technicolor), E0:B9:E5 (Technicolor 789vac v2), ..., the keyspace is 0123456789ABCDEF 10 length.

NOS is a fusion between ZON (formely known as PT Multimedia - cable tv), Optimus (mobile internet and voice), Clix (adsl internet), and some more few small comunications companies. These companies's DNS names are still maintained as of today. Huawei mobile internet modems are usually offered to the clients.
NOS_Internet_xxxx where x is 0-9A-F. Routers starting with 70:8A:09 (Huawei B310) keyspace 0-9 8 length.
WiFi_xxxx where x is 0-9A-F. Routers starting with 3C:47:11 (Huawei B315) Keyspace is 0-9A-Z 11 length.

**Comment by soxrok2212** [comment]
Please submit a pull request with the proposed changes!
