### ISSUE TITLE
clarify usage in help

### ISSUE THREAD

**Issue by resistor4u** [soxrok2212/PSKracker#8]
could you please include more concrete examples in the brief usage text? what does a "target" look like? should we include colons when giving the MAC addy?

**Comment by soxrok2212** [comment]
Sure, I will add those in the next commit. For now, there is a built in MAC address parser... the formats xx:xx:xx... xx-xx-xx... xxxxxx... should work.
The current supported targets are:
```
nvg589
nvg599
dpc3939
dpc3941
tg1682g
```

For ATT:
```
$ pskracker -t nvg599
...
aabtp?sfrhuk
aabtqbeddgev
aabtqc7a6e56
aabtqes=sdqa
aabtqge%ecaj
aabtqh787azu
aabtqjt6s?j5
aabtqmf4e+#?
aabtqn8z7%vi
aabtqquxt#ft
aabtqsgvf864
...
```

For Xfinity,
```
$ pskracker -t dpc3941 -b 11-22-33-44-55-66
PSK: 5756C3915966657704
```

**Comment by soxrok2212** [comment]
Should be good to go with https://github.com/soxrok2212/PSKracker/commit/73ce87de5511b80670b5807dca109d81f82a515d

**Comment by soxrok2212** [comment]
Will also probably move the supported models and a more thorough list of usage examples (when more models are supported) to a wiki, if and when I ever get around to making one.

**Comment by soxrok2212** [comment]
I've updated the wiki [here](https://github.com/soxrok2212/PSKracker/wiki/Attack-Types-and-Supported-Models) in case you were still looking for this.

**Comment by darknodi** [comment]
@soxrok2212 i have followings your declarations. error result. 

should chmod 777 foldername 

should sudo make 
sudo make install 

@soxrok2212
